version = 0.1

[default.deploy.parameters]
stack_name = "task-manager"
resolve_s3 = true
s3_prefix = "task-manager"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "TableName=\"TaskTable\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
